<a href="https://colab.research.google.com/github/iqiirascal-lgtm/DAA/blob/main/DAA_Pertemuan_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#List Contoh

aList = ["Jhon", 33, "Toronto", True]
print(aList)

['Jhon', 33, 'Toronto', True]


In [ ]:
from datetime import datetime
tglv1 = datetime.now()
print(tglv1)

import datetime as vDate
hari = vDate.datetime.now()
print(hari)

tanggal = vDate.datetime.today()
print(hari)
print(tanggal)

Mahasiswa = ["Reezqee", "2024071021", "Informatika", "DAA", f"{tanggal.day}-{tanggal.month}-{tanggal.year}", "Universitas Pembangunan Jaya"]
print(Mahasiswa)

2025-09-15 09:24:43.940874
2025-09-15 09:24:43.941026
2025-09-15 09:24:43.941026
2025-09-15 09:24:43.941123
['Reezqee', '2024071021', 'Informatika', 'DAA', '15-9-2025', 'Universitas Pembangunan Jaya']


In [ ]:
#Latihan List Mahasiswa

Mahasiswa = ["Reezqee", "2024071021", "Informatika", "Algoritma", "15-09-2025", "Universitas Pembangunan Jaya"]
print(Mahasiswa)

['Reezqee', '2024071021', 'Informatika', 'Algoritma', '15-09-2025', 'Universitas Pembangunan Jaya']


In [ ]:
#List Index

bin_colors=['Red', 'Green', 'Blue', 'Yellow']
bin_colors[1]

'Green'

In [ ]:
#Latihan List Index

print("NIM", Mahasiswa[1])
print("Universitas", Mahasiswa[5])

NIM 2024071021
Universitas Universitas Pembangunan Jaya


In [ ]:
#List Slicing

bin_colors=['Red', 'Green', 'Blue', 'Yellow']
bin_colors[0:2]

['Red', 'Green']

In [ ]:
#Latihan List Slicing

print("NIM & Prodi", Mahasiswa[1:3])

NIM & Prodi ['2024071021', 'Informatika']


In [ ]:
#List Iterasi

bin_colors=['Red', 'Green', 'Blue', 'Yellow']
for aColor in bin_colors:
  print(aColor + " Square")

Red Square
Green Square
Blue Square
Yellow Square


In [ ]:
#Latihan List Iterasi

for aMhs in Mahasiswa:
  print("UPJ", aMhs)

UPJ Reezqee
UPJ 2024071021
UPJ Informatika
UPJ DAA
UPJ 15-9-2025
UPJ Universitas Pembangunan Jaya


In [ ]:
#TUPLES

UPJ = ( 'Universitas', 'Pembangunan', 'Jaya')
for aUPJ in UPJ:
  print(aUPJ + ' UPJ')

Universitas UPJ
Pembangunan UPJ
Jaya UPJ


In [ ]:
# Latihan Tuple
nested_tuple = (100, (200, 400, 600), 300, (400, 800))
print(nested_tuple)


(100, (200, 400, 600), 300, (400, 800))


In [ ]:
#Dictionary

bin_colors = {
"manual_color": "Yellow",
"approved_color": "Green",
"refused_color": "Red"}
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Green', 'refused_color': 'Red'}


In [ ]:
bin_colors.get('approved_color')

'Green'

In [ ]:
bin_colors['approved_color']

'Green'

In [ ]:
bin_colors['approved_color']="Purple"
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Purple', 'refused_color': 'Red'}


In [32]:
#Latihan Dictionary

mahasiswa_dictionary = {
    "Nama": "Reezqee Rascal Gultom",
    "NIM": "2024071021",
    "Prodi": "Informatika",
    "Universitas": "UPJ"
}
mahasiswa_dictionary

{'Nama': 'Reezqee Rascal Gultom',
 'NIM': '2024071021',
 'Prodi': 'Informatika',
 'Universitas': 'UPJ'}

In [33]:
#Set

green = {'grass', 'leaves', 'leaves'}
print(green)

{'leaves', 'grass'}


In [34]:
green = {'grass', 'leaves', 'leaves'}
print(green)

{'leaves', 'grass'}


In [35]:
#Latihan Set

yellow = {'dandelions', 'leaves', 'fire hydrants'}
red = {'leaves', 'fire hydrants', 'rose', 'blood'}

combine = yellow|red
pisah = yellow&red
print(yellow)
print(red)
print(combine)
print(pisah)


{'fire hydrants', 'leaves', 'dandelions'}
{'fire hydrants', 'rose', 'leaves', 'blood'}
{'dandelions', 'blood', 'fire hydrants', 'rose', 'leaves'}
{'fire hydrants', 'leaves'}


In [36]:
#Data Frames

import pandas as pd
df = pd.DataFrame([
    ['1', 'Fares', 32, True],
    ['2', 'Elena', 23, False],
    ['3', 'Steven', 40, True]])
df

0       1   2      3
0  1   Fares  32   True
1  2   Elena  23  False
2  3  Steven  40   True

In [38]:
df.columns = ['id', 'name', 'age', 'decision']
df

id    name  age  decision
0  1   Fares   32      True
1  2   Elena   23     False
2  3  Steven   40      True

In [39]:
df.iloc[:,3]

0     True
1    False
2     True
Name: decision, dtype: bool

In [41]:
#Latihan DataFrames

import pandas as pd

data = {
    "No": [1, 2, 3],
    "Prodi": ["Informatika", "Sistem Informasi", "Teknik Sipil"],
    "Mahasiswa": [50, 55, 40],
    "Laki-laki": [30, 30, 30],
    "Perempuan": [20, 25, 10]
}

mhs = pd.DataFrame(data)
print(mhs)


   No              Prodi  Mahasiswa  Laki-laki  Perempuan
0   1        Informatika         50         30         20
1   2   Sistem Informasi         55         30         25
2   3       Teknik Sipil         40         30         10


In [42]:
#Matrix

import numpy as np
myMatrix = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
print(myMatrix)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [43]:
print(type(myMatrix))

<class 'numpy.ndarray'>


In [45]:
#Latihan matrix

import numpy as np

matrix = np.array([[100, 200, 300],
                   [700, 600, 500],
                   [900, 1000, 800]])

print("Matrix asli:\n", matrix)
print("Transpose:\n", matrix.T)


Matrix asli:
 [[ 100  200  300]
 [ 700  600  500]
 [ 900 1000  800]]
Transpose:
 [[ 100  700  900]
 [ 200  600 1000]
 [ 300  500  800]]


In [46]:
#Stack(LIFO)

#Vector Menggunakan list python
myVector = [22, 33, 44, 55]
print(myVector)

[22, 33, 44, 55]


In [47]:
print(type(myVector))

<class 'list'>


In [48]:
#Menggunakan array numpy

myVector = np.array([22, 33, 44, 55])
print(myVector)

[22 33 44 55]


In [49]:
print(type(myVector))

<class 'numpy.ndarray'>


In [50]:
class stack:
  def __init__(self):
    self.items = []
  def isEmpty(self):
    return self.items == []
  def push(self, item):
    self.items.append(item)
  def pop(self):
    return self.items

In [51]:
class queue:
  def __init__(self):
    self.items = []
  def isEmpty(self):
    return self.items == []
  def enqueue(self, item):
    self.items.insert(0, item)

In [52]:
class Queue:
    def __init__(self):
        self.items = []

    def isEmpty(self):
        return self.items == []

    def enqueue(self, item):
        self.items.insert(0, item)

    def dequeue(self):
        return self.items.pop()

    def size(self):
        return len(self.items)

# Contoh penggunaan
q = Queue()
q.enqueue("A")
q.enqueue("B")
print(q.dequeue())  # Output: A


A
